exports.resmessage = {
    deletedrecord: "This record does not exist or has been deleted.",
    useradded: "User added successfully.",
    userupdated: "User updated successfully.",
    userstatus: "User status changed successfully.",
    userdeleted: "User deleted successfully.",
    userwronginfo: "User mobile number or password invalid.",
    usernotfound: "User not found!",
    userlogin: "User logged in successfully",
    mobilealreadyexists: "Mobile number already exists.",
    useraddressadded: "User Address added successfully.",
    useraddressupdated: "User Address updated successfully.",
    useraddressstatus: "User Address status changed successfully.",
    useraddressdeleted: "User Address deleted successfully.",
    useraddressdefault: "Default User Address updated successfully.",
    productcategoryadded: "Product Category added successfully.",
    productcategoryupdated: "Product Category updated successfully.",
    productcategorystatus: "Product Category status changed successfully.",
    productcategorydeleted: "Product Category deleted successfully.",
    productdiscountadded: "Product Discount added successfully.",
    productdiscountupdated: "Product Discount updated successfully.",
    productdiscountstatus: "Product Discount status changed successfully.",
    productdiscountdeleted: "Product Discount deleted successfully.",
    productdiscountnotexists: "Product Discount does not exists or is inactive.",
    productinventoryadded: "Product Inventory added successfully.",
    productinventoryupdated: "Product Inventory updated successfully.",
    productinventorystatus: "Product Inventory status changed successfully.",
    productinventorydeleted: "Product Inventory deleted successfully.",
    productadded: "Product added successfully.",
    productupdated: "Product updated successfully.",
    productstatus: "Product status changed successfully.",
    productdeleted: "Product deleted successfully.",
    usercartadded: "User cart added successfully.",
    usercartupdated: "User cart updated successfully.",
    usercartstatus: "User cart status changed successfully.",
    usercartdeleted: "User cart deleted successfully.",
    userwishlistadded: "User wishlist added successfully.",
    userwishlistupdated: "User wishlist updated successfully.",
    userwishliststatus: "User wishlist status changed successfully.",
    userwishlistdeleted: "User wishlist deleted successfully.",
    orderadded: "Order added successfully.",
    orderupdated: "Order updated successfully.",
    orderstatus: "Order status changed successfully.",
    orderdeliverystatus: "Order delivery status changed successfully.",
    orderdeleted: "Order deleted successfully.",
    orderfailed: "Order failed. No items in the cart.",
    orderitemsadded: "Order items added successfully.",
    orderitemsupdated: "Order items updated successfully.",
    orderitemsstatus: "Order items status changed successfully.",
    orderitemsdeleted: "Order items deleted successfully.",
    paymentadded: "Payment added successfully.",
    paymentupdated: "Payment updated successfully.",
    paymentstatus: "Payment status changed successfully.",
    paymentdeleted: "Payment deleted successfully.",
    paymentfailed: "Payment failed! Please place the order again.",
    orderproductnotremoved: "Products not reduced.",
}